name: Log Environment Variable

on:
  push:
    branches:
      - main  # main branch'e push yapıldığında tetiklenecek

jobs:
  log-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log Environment Variable
        run: |
          echo "The value of MY_ENV_VAR is: ${{ secrets.MY_ENV_VAR }}"
